In [2]:
!pip install opencv-contrib-python

  Obtaining dependency information for opencv-contrib-python from https://files.pythonhosted.org/packages/aa/2e/576ac47f21d555b459ca837bb3fb937e50339b8fbfd294945ea2f5290416/opencv_contrib_python-4.9.0.80-cp37-abi3-win_amd64.whl.metadata
  Using cached opencv_contrib_python-4.9.0.80-cp37-abi3-win_amd64.whl.metadata (20 kB)
   ---------------------------------------- 0.0/45.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/45.3 MB ? eta -:--:--
   ---------------------------------------- 0.1/45.3 MB 1.7 MB/s eta 0:00:28
   ---------------------------------------- 0.2/45.3 MB 2.1 MB/s eta 0:00:22
   ---------------------------------------- 0.5/45.3 MB 3.1 MB/s eta 0:00:15
    --------------------------------------- 0.9/45.3 MB 4.5 MB/s eta 0:00:10
   - -------------------------------------- 1.7/45.3 MB 6.3 MB/s eta 0:00:07
   -- ------------------------------------- 3.0/45.3 MB 9.6 MB/s eta 0:00:05
   ---- ----------------------------------- 4.9/45.3 MB 14.3 MB/s eta 0:00

In [1]:
import cv2
import matplotlib.pyplot as plt
import numpy as np

### Reading images

In [2]:
img=cv2.imread('photos.jpg')

### Displaying images in python

In [3]:
cv2.imshow('hello',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Saving images

In [4]:
status=cv2.imwrite(r'D:\Computer vision\photos.jpg',img)
status=cv2.imwrite('Images.jpg',img)
print('Image written success? :',status)

Image written success? : True


In [5]:
print(img)

[[[196 182 159]
  [200 188 164]
  [198 191 166]
  ...
  [ 30  68  46]
  [151 165 147]
  [183 186 170]]

 [[195 181 158]
  [198 186 162]
  [198 191 166]
  ...
  [ 11  42  21]
  [119 131 113]
  [179 180 164]]

 [[197 183 160]
  [195 183 159]
  [196 186 162]
  ...
  [ 14  36  17]
  [100 106  87]
  [188 186 168]]

 ...

 [[ 22 132 108]
  [  4 116  92]
  [  0 116  93]
  ...
  [  9 139 114]
  [  4 151 129]
  [  2 159 139]]

 [[ 16 125  99]
  [  1 111  87]
  [  0 107  85]
  ...
  [  9 137 112]
  [  0 145 123]
  [  0 150 131]]

 [[  8 117  91]
  [  0 105  82]
  [  0 100  78]
  ...
  [  9 137 112]
  [  0 142 120]
  [  0 146 127]]]


### Converting image to greyscale

In [6]:
imgGray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
cv2.imshow('Gray image',imgGray)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [7]:
print(imgGray)

[[177 182 184 ...  57 158 181]
 [176 180 184 ...  32 124 175]
 [178 177 180 ...  28 100 181]
 ...
 [112  96  96 ... 117 128 135]
 [105  91  88 ... 115 122 127]
 [ 97  86  82 ... 115 119 124]]


### Edge detecton

In [8]:
imgCanny=cv2.Canny(img,150,250)
cv2.imshow('Canny image',imgCanny)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Croping image

In [9]:
width,height=250,350
point1=np.float32([[111,219],[287,188],[154,482],[352,440]])
point2=np.float32([[0,0],[width,0],[0,height],[width,height]])
matrix=cv2.getPerspectiveTransform(point1,point2)
cropped=cv2.warpPerspective(img,matrix,(width,height))

cv2.imshow('output',cropped)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Access image properties

In [10]:
print(img.shape)

#extracting the height and width of an image
h,w=img.shape[:2]
# displaying the height and width
print('Height={},Width={}'.format(h,w)) #*(3-color,1-gray)

(510, 1020, 3)
Height=510,Width=1020


In [11]:
print(img.size)

1560600


In [12]:
print(img.dtype)

uint8


### Extracting the Region Of Interest(ROI)

In [13]:
# we will calculate the ROI
# by slicing the pixels of the image
roi=img[100:500,200:700]
cv2.imshow('image',roi)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Resizing the image

In [14]:
# resize() function takes 2 parameters, the image and the dimensions
resize=cv2.resize(img,(500,500))
cv2.imshow('image',resize)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [15]:
print(resize.shape)

(500, 500, 3)


In [16]:
w=1020
h=510
# calculating the ratio
ratio=500/w
# creating a tuple containing width and height
dim=(500,int(h*ratio))

#resize the image
resize_aspect=cv2.resize(img,dim)

cv2.imshow('image',resize_aspect)
cv2.waitKey(0)
cv2.destroyAllWindows()

print(resize_aspect.shape)

(250, 500, 3)


### Rotating the image

In [17]:
w=1020
h=510
# calculating the center of the image
center=(w//2,h//2)

# generating a rotation matrix
matrix=cv2.getRotationMatrix2D(center,-90,1.0)

#performing the affine transformation
rotated=cv2.warpAffine(img,matrix,(w,h))

cv2.imshow('image',rotated)
cv2.waitKey(0)
cv2.destroyAllWindows()

### drawing Rectangle

In [18]:
# we are coping the original image, as it is an in=place operation.
output=img.copy()

# using the rectangle function to create a rectangle
rectangle=cv2.rectangle(output,(660,250),(350,10),(255,0,0),2)

cv2.imshow('image',rectangle)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Drawing circle

In [51]:
output=img.copy()
circle=cv2.circle(output,(500,250),257,(255,0,0),2)

cv2.imshow('image',circle)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Drawing poylines

In [68]:
output=img.copy()
#defining points for polylines
pts=np.array([[300,100],[400,300],[900,300],[600,200]],np.int32)

poly=cv2.polylines(output,[pts],True,(0,255,255),3)
cv2.imshow('image',poly)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Displaying Text

In [28]:
output=img.copy()

text=cv2.putText(output,'Panda',(50,500),cv2.FONT_HERSHEY_SIMPLEX,4,(255,0,0),2)
cv2.imshow('image',output)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Tresholding

In [69]:
imgGray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
# threshold the image by setting all pixel values less than 225
# to 255 (white;foreground),and all pixel values >= 225 to255
# (black; background),therby segmenting the image

thresh=cv2.threshold(imgGray,50,255,cv2.THRESH_BINARY_INV)[1]
cv2.imshow('THRESH',thresh)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Playing video using video capture () function

In [38]:
cap=cv2.VideoCapture('PROJECT.mp4')
# check if camera opened successfully

if (cap.isOpened()==False):
    print('Error opening video file')
# read until video is complicated
while(cap.isOpened()):
# capture frame by frame
    ret,frame=cap.read()
    if ret==True:
        #displaying the resulting frame
        cv2.imshow('Frame',frame)
        #press Q on keyboard to exit
        if cv2.waitKey(25) & 0xFF ==ord('q'):
            break #break the loop
            
    else:
        break
#when everything done,release
# the video capture object
cap.release()
# close all the frames
cv2.destroyAllWindows()

In [ ]:
### Capture camera

In [39]:
cap=cv2.VideoCapture(0)
# check if camera opened successfully

if (cap.isOpened()==False):
    print('Error opening video file')
# read until video is complicated
while(cap.isOpened()):
# capture frame by frame
    ret,frame=cap.read()
    if ret==True:
        #displaying the resulting frameq
        cv2.imshow('Frame',frame)
        #press Q on keyboard to exit
        if cv2.waitKey(25) & 0xFF ==ord('q'):
            break #break the loop
            
    else:
        break
#when everything done,release
# the video capture object
cap.release()
# close all the frames
cv2.destroyAllWindows()

## Saving video

In [ ]:
cap=cv2.VideoCapture(0)
fourcc=cv2.VideoWriter_fourcc(*'XVID')
out=cv2.VideoWriter('output.avi',fourcc,20.0,(640,480))

while(cap.isOpened()):
    ret,frame=cap.read()
    if ret==True:
        #write the flipped frame
        out.write(frame)
        #press Q on keyboard to exit
        if cv2.waitKey(1) & 0xFF ==ord('q'):
            break #break the loop
            
    else:
        break

# release everything if job is finished
cap.release()
out.release()
cv2.destroyAllWindows()